### ISSUE TITLE
Minimum PHP Version

### ISSUE THREAD

**Issue by phptek** [silverstripe-australia/silverstripe-queuedjobs#358]
Is there a reason this module specifies PHP `^7.1`? I have an upcoming Silverstripe 4.9 / PHP8 project looking to consume `silverstripe/staticpublishqueue` which depends on `symbiote/silverstripe-queuedjobs`. Could composer be tweaked to accept e.g. `"php": ">=7.1"`?

**Comment by emteknetnz** [comment]
Unit tests are passing on php8 https://app.travis-ci.com/github/symbiote/silverstripe-queuedjobs/jobs/533863806

This would require a new minor release of queuedjobs, we've done changes in php versions as minor releases in the past - https://docs.silverstripe.org/en/4/changelogs/4.7.0/#support-for-php-8

I can't self-merge PR's, so if someone could raise I a PR for this I'll merge it.  Make the requirement `"^7.1 || ^8",` so that we don't automatically assume that things work on php9

**Comment by michalkleiner** [comment]
`^7.1 || ^8.0`, when it's just `^8` it doesn't go past 8.0.x, even when some constraints validators say it should, Composer doesn't play ball.

**Comment by emteknetnz** [comment]
Weird. `^8` and `^8.0` should be functionally identical

`^7.1 || ^8.0` reads slightly better so that's a bonus

**Comment by GuySartorelli** [comment]
PR was merged. Closing this issue
